### ISSUE TITLE
TypeError: Cannot destructure property 'onGestureHandlerStateChange' of 'this.ref.props' as it is undefined.

### ISSUE THREAD

**Issue by hamidfzm** [software-mansion/react-native-gesture-handler#1164]
This is a bug in react native web. I want to detect double tap using *TapGestureHandler*. It works perfectly fine in Android and iOS but in Web, I get this error:
```
TypeError: Cannot destructure property 'onGestureHandlerStateChange' of 'this.ref.props' as it is undefined.
TapGestureHandler.GestureHandler.sendEvent
node_modules/react-native-gesture-handler/web/GestureHandler.js:151
  148 | 
  149 | sendEvent = nativeEvent => {
  150 |   const {
> 151 |     onGestureHandlerStateChange: onHandlerStateChange,
      | ^  152 |     onGestureHandlerEvent: onGestureEvent,
  153 |   } = this.ref.props;
  154 | 
```
## Versions
react-native: 0.62.2
react-native-web: 0.13.6
react-native-gesture-handler: 1.7.0

## Sample code to generate issue
```typescript
// Tapper.tsx
import React from 'react';
import {
  State,
  TapGestureHandler,
  TapGestureHandlerStateChangeEvent,
} from 'react-native-gesture-handler';

type Props = {
  onSingleTap?: () => void;
  onDoubleTap?: () => void;
  children: React.ReactNode;
};

const Component: React.FC<Props> = ({ children, onDoubleTap, onSingleTap }) => {
  const doubleTapRef = React.useRef<TapGestureHandler>();
  const handleSingleHandlerStateChange = React.useCallback(
    (event: TapGestureHandlerStateChangeEvent) => {
      if (event.nativeEvent.state === State.ACTIVE) {
        onSingleTap?.();
      }
    },
    [onSingleTap]
  );

  const handleDoubleHandlerStateChange = React.useCallback(
    (event: TapGestureHandlerStateChangeEvent) => {
      if (event.nativeEvent.state === State.ACTIVE) {
        onDoubleTap?.();
      }
    },
    [onDoubleTap]
  );

  return (
    <TapGestureHandler
      onHandlerStateChange={handleSingleHandlerStateChange}
      waitFor={doubleTapRef}
    >
      <TapGestureHandler
        // @ts-ignore
        ref={doubleTapRef}
        onHandlerStateChange={handleDoubleHandlerStateChange}
        numberOfTaps={2}
      >
        {children}
      </TapGestureHandler>
    </TapGestureHandler>
  );
};

Component.displayName = 'Tapper';

export default Component;
```

Just use this component with any component in web.

**Comment by amattice-pfct** [comment]
Hi, I had investigated this issue for one of our projects and thought I would post my findings. I don't think we will be able to commit time to posting a PR, but I've at least diagnosed the problem. This may be of help to others and the maintainers. 

We recently updated a project from React Native Web from 0.12 to 0.13, and then needed to downgrade. [In the release notes, it seems that RNW has changed which props it is forwarding through its refs to the DOM](https://github.com/necolas/react-native-web/releases/tag/0.13.0). It seems that there are a few places in the `react-native-gesture-handler` web code where it is accessing these props through the ref.

As a temporary workaround, downgrading to 0.12 stops the crash for the time being, with the caveat that you're missing compatibility with changes from later RN versions (ex: no `Pressable`, if I'm not mistaken). Later this week, if it's deemed helpful, I can try to find the spots in the codebase where these references are at least occurring if it will help speed up the creation of a patch.

**Comment by emech-en** [comment]
I had the same problem. 

Downgrading react-native-web to 0.12.3 solved my problem.

**Comment by janicduplessis** [comment]
I was able to work the issue by making sure the children of GestureHandler components is a class that renders a View

Something like this works:

```ts
class NonForwardedRefAnimatedViewHack extends React.Component<any> {
  render() {
    return <Animated.View {...this.props} />;
  }
}
```

**Comment by Shafran123** [comment]
Same issue i got

**Comment by hunght** [comment]
same here i'm using expo sdk version 39.0.2,

**Comment by AlastairTaft** [comment]
@janicduplessis You legend. That avoids me having to downgrade.

**Comment by fortezhuo** [comment]
@AlastairTaft / @janicduplessis 
I can't get Swipeable Component works with that trick.. Can you give me some clue ?

**Comment by AlastairTaft** [comment]
@fortezhuo I spoke to soon. You're right, I don't get runtime errors anymore but nothing works.

**Comment by difaananda40** [comment]
I'm facing this problem right now, any solution please?

**Comment by hosseinmd** [comment]
I have the same problem.

"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-scripts": "4.0.0",
"react-native-web": "^0.14.4",

**Comment by keziabaidoo** [comment]
Cannot read property 'onGestureHandlerStateChange' of undefined
    at NativeViewGestureHandler.GestureHandler.sendEvent

need help please

**Comment by jjborie** [comment]
@keziabaidoo , the bug has been fixed yesterday use:

"react-native-gesture-handler": "github:software-mansion/react-native-gesture-handler#196782c740cde1464e4ce4f5f46bf2c756ecdc43",

It work for me.

**Comment by keziabaidoo** [comment]
did not work
for me

**Comment by milkcha** [comment]
same problem.

**Comment by monjohn** [comment]
Latest master did not fix the problem for me, but downgrading to 12.3 did.

**Comment by chaaya** [comment]
There is a new version out there with a fix for it according to the changelog.

https://github.com/software-mansion/react-native-gesture-handler/releases/tag/1.9.0

**Comment by keziabaidoo** [comment]
Thank u

**Comment by kwoxer** [comment]
I'm getting this `Uncaught TypeError: can't access property "onGestureHandlerStateChange", _this$ref$props is undefined` error on any of these `react-native-web` version:

"react-native-web": "~0.14.4",
"react-native-web": "~0.13",
"react-native-web": "~0.12",

I'm using:
- "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz",
- "react-native-gesture-handler": "~1.8.0",

**Comment by kwoxer** [comment]
Ahh sorry, didn't see that the fix happened in `react-native-gesture-handler`.

Upgrading to
"react-native-gesture-handler": "~1.9.0",
fixed the issue.

**Comment by VelislavP** [comment]
When I try to start my expo project I get this error:

Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-gesture-handler - expected version range: ~1.8.0 - actual version installed: ~1.9.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]

Package versions:

"expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "firebase": "7.9.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.9.0",

This happened after I upgraded to "react-native-gesture-handler": "~1.9.0"

My app wasn't working with version "~1.8.0" and I don't know what to do.
Does anyone have an idea how can I fix this... please?
