### ISSUE TITLE
Doesn't work in a modal

### ISSUE THREAD

**Issue by martinezguillaume** [software-mansion/react-native-gesture-handler#139]
Hi !
I have a little issue on Android, `onGestureEvent` is not trigger when GestureHandler components is on a modal on Android. When I change the modal to a View, it works perfectly 👌

No problem on iOS

**Comment by mordaha** [comment]
+1 
any workaround?

**Comment by martinezguillaume** [comment]
I don’t use Modal for now, I just re-create it with a View in absolute position

**Comment by csto** [comment]
+1

**Comment by osdnk** [comment]
Hi, @martinezguillaume, @mordaha, @csto 
I did take a look on this issue and I suppose it's not a matter of our library, but RN Core.

**Comment by mars-lan** [comment]
@osdnk is this fixable?

**Comment by ParhamZare** [comment]
+1 gesture does not work on modal

**Comment by ewendel** [comment]
I also ran into this bug today.

**Comment by Via-profit** [comment]
Same problem. Gesture does not work on modal on **Android**.
[Expo for example](https://snack.expo.io/@vas-vas/rn-gesture-handler-issue-139)

**Comment by Dmitrylolo** [comment]
Same for me. Tested react-native's PanResponder handlers on modal - works fine.

**Comment by Dmitrylolo** [comment]
It even not works on react-navigation new screen. Ie 
```
const RootStack = createStackNavigator({
  App: {
    screen: AppNavigator,
  },
  UploadPhoto: {
    screen: UloadPhoto,
  },
  AddExercise: {
    screen: AddExercise,
  },
});
``` 
not works on UploadPhoto and AddExercise, when navigating from screen from AppNavigator stack

**Comment by LaVielle** [comment]
I was using a standard React Native `Modal` and was experiencing this issue.
I worked around the problem by creating a new screen and displaying it as a modal. I'm using [react-native-navigation](https://wix.github.io/react-native-navigation), so:
```JavaScript
Navigation.showModal({
    component: {
      name: navRoutes.ImageModal,
      passProps: { image },
    },
  })
```
Gestures are working as expected on both iOS and Android, and I still get transparent background that I wanted from my original modal.

**Comment by osdnk** [comment]
I have dug into it for a while.

1. It's a problem of RNGH. Sorry 😒 
2. It happens bc modals are not rendered below an RN root view. 
3. It's fixable by replacing modals' mechanism in a similar way as we do with an RNRootView by wrapping it with some extra logic.
4. I have no time to do it now, it's time-consuming work and probably requires copying some code in RNGH code on Android native side.

If someone wants and has time to do it, I'll happily review it and merge immediately if it would be workable and not too hacky.

@martinezguillaume @mordaha @csto @mars-lan @ParhamZare @ewendel @Via-profit @Dmitrylolo @LaVielle

**Comment by osdnk** [comment]
Also, I've made a try two months ago.

 https://github.com/kmagiera/react-native-gesture-handler/commit/139da18039683bed3c439c991c7eaf802086bf86
 
Maybe it could be an inspiration for someone 🤷‍♂️

**Comment by AlexUzan** [comment]
Hey @osdnk I need this feature for my app, so I was thinking I could give it a try, but I don't have a lot of experience with RNGestureHandler, or with Android. Could you give me some more insight on what I would need to do to make it work ?
Also I was looking at your previous try, and I would like to know what's missing for it to be finished, and if it could be used as a starting point.

**Comment by yqz0203** [comment]
same error.

**Comment by paolospag** [comment]
@kmagiera @osdnk any update on this?
even `Touchable*`'s don't work inside the modal and this is frustrating

**Comment by blohamen** [comment]
+1. i use reanimated-bottom-sheet with modal

**Comment by cristianoccazinsp** [comment]
Any updates? Or perhaps, any other modal component that does not suffer from this issue? RN's modal honestly works like quite bad and is full of bugs (such as getting stuck if combined with an alert)

**Comment by mars-lan** [comment]
@cristianoccazinsp I ended up using https://github.com/react-native-community/react-native-modal

**Comment by cristianoccazinsp** [comment]
Odd. That component is supposed to use react's modal internally. Did it
make a difference to you?

**Comment by mars-lan** [comment]
@cristianoccazinsp It only uses RN's modal to cover the screen, which can be disabled by setting `coverScreen` to `false`

**Comment by jvaclavik** [comment]
> @cristianoccazinsp It only uses RN's modal to cover the screen, which can be disabled by setting `coverScreen` to `false`

But is there a way how to show fullscreen modal with this prop which is not rendered in root component of the app?

**Comment by mars-lan** [comment]
@jvaclavik I used it in conjunction with https://github.com/callstack/react-native-paper, which has a component called [Portal](https://callstack.github.io/react-native-paper/portal.html) designed specifically for this purpose.

**Comment by owinter86** [comment]
This may not resolve all use cases but you can enable gestures in react native modal when setting the prop `propagateSwipe` to true.

**Comment by qalqi** [comment]
This issue seems to be related to https://github.com/kmagiera/react-native-screens/issues/61

Don't use react native screens in android. Tested and working fine with 'reanimated-bottom-sheet'

if (Platform.OS === 'ios') {
    useScreens();
}

This React Navigation Modal config for transparent bg is 

 ScreenOne: {
            screen: ScreenOne,
            navigationOptions: {
                gesturesEnabled: false
            },
        }
{
        mode: 'modal',
        transparentCard: true,
        headerMode: 'none',
        cardStyle: {
            backgroundColor: 'transparent',
            opacity: 1
        },
        transitionConfig: () => ({
            containerStyle: {
                backgroundColor: 'transparent',
            }
        })
    }

**Comment by djorkaeffalexandre** [comment]
@osdnk fixed it?

**Comment by romanonthego** [comment]
This one is was so much pain.
I've spend some time before resolving to google it, pull my hairs out trying to figure out why on earth same component works on iOS and on android but only in some places inside application

**Comment by deflorilemarului** [comment]
we have the same issue - it doesn't work on modal.
i wonder if anyone is working on this or know of any status update ?
do we need to drop this library and switch to RN pan handlers ?
any suggestion ?

**Comment by kesha-antonov** [comment]
https://github.com/react-native-community/react-native-modal doesn't work too

**Comment by fauker** [comment]
Same here. RectButton doesn't work inside https://github.com/react-native-community/react-native-modal

**Comment by romanonthego** [comment]
@deflorilemarului @kesha-antonov @fauker 
Will spare you some time, neither `Modal`, nor  `Modal`-based packages (if they don't require you to link native dependencies - they are based on `react-native`'s `Modal`) will help you (I've tried all of them, basically).
All of `gesture-` related components (bottomsheet-behaviour for us) will not register any touches/swipes etc when rendered inside `<Modal>...</Modal>` on android;
There is 3 solutions I can think of:
1. Use any other library if you are using modals. You may require rewrite some swipe-based components to `PanResponder`; this on is pain, but pretty straightforward;
2. Use modals that are `portals`. They are not actually portals nor modals- portals are not supported by react-native because there is single application host - but they are working by placing Host Component somewhere up your application and renders Modal content in absolute view above app stack; this one is working solution, but you will loose any `useContext()` calls due to children being rendered above context providers; does not work for us, since `navigation` context is lost;
3. Use modals provided by navigation library (`react-navigation`); this one works, but API is... not good - for one you could not make a single screen a modal, only a stack can be in modal mode; this one is solution I stick with.

Well, there is final solution - patch native android implementation (not possible if you are using expo) or wait for patch in a library and then wait until it merged into expo.

p.s.
Don't get me wrong, this library is amazing, and I cannot stress enough how much I appreciate work being poured into this and how much better the experience for end user, but bugs like this one make me want to pull my hairs out.

**Comment by radinreth** [comment]
Few libraries requires us to deal with native context, if so:

For android, we will need a special care **as stated** in [RNGH document](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html):

Update your ```MainActivity.java``` file
<img width="810" alt="Screen Shot 2019-11-30 at 12 17 07 PM" src="https://user-images.githubusercontent.com/5484758/69895941-9b878600-136b-11ea-9419-bdc8cab4679e.png">

Hope it helps

**Comment by jeffdico** [comment]
> Few libraries requires us to deal with native context, if so:
> 
> For android, we will need a special care **as stated** in [RNGH document](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html):
> 
> Update your `MainActivity.java` file
> <img alt="Screen Shot 2019-11-30 at 12 17 07 PM" width="810" src="https://user-images.githubusercontent.com/5484758/69895941-9b878600-136b-11ea-9419-bdc8cab4679e.png">
> 
> Hope it helps

Yes, this worked perfectly for me. I almost got frustrated looking for solutions on making my android app swippable.

**Comment by RZsam** [comment]
still not working
if change modal to view everything work just fine...

**Comment by Psiiirus** [comment]
Hi @romanonthego ,
> Well, there is final solution - patch native android implementation (not possible if you are using expo) or wait for patch in a library and then wait until it merged into expo.

Can you please tell me what to patch in side my native android code?

**Comment by osdnk** [comment]
whop https://github.com/software-mansion/react-native-gesture-handler/pull/937

**Comment by grahammendick** [comment]
@osdnk That's exciting. Will it work with a `DialogFragment` as well?

**Comment by samcampisi** [comment]
After trying #937 I found out it didn't work for me...

Maybe it's because I'm using wix's react-native-navigation? As far as I know each and every screen is registered with the gestureHandlerRootHOC (the library works perfectly with normal, non modal views).

This is a fragment of the screen in which I tried the RectButton in a Modal (basically as it is in the doc update)

```
  renderSearchScreen = () => {
    const { showSearchHistory } = this.state;
    const ExampleWithHoc = gestureHandlerRootHOC(() => {
      return (
        <View style={genericStyles.container}>
          <SearchScreen
            searchBar={{
              ...this.searchBar,
              searchQuery: this.props.searchQuery,
            }}
            onBackPress={() => {
              this.setState({ showSearchHistory: false });
            }}
          />
        </View>
      );
    });

    if (showSearchHistory) {
      return (
        <RNModal
          animationType="fade"
          transparent
          visible={this.state.showSearchHistory}
          onRequestClose={() => {}}>
          <ExampleWithHoc />
        </RNModal>
      );
    }

    return null;
  };
```

The modal loads when it's supposed to, but the RectButton does not fire the onPress event. I tried making a minimum reproducible demo with a brand new app but then I ran into #848 #676 #835 (possible duplicates of one another).

**Comment by mxmzb** [comment]
> whop #937

That's amazing! It still doesn't work with [`react-native-modal`](https://github.com/react-native-community/react-native-modal) for me, though!

**Comment by mb389** [comment]
I'm still having issues with this even after upgrading to 1.6.0 and implementing the documented solution. while the gestures are working, i'm seeing a lot of buggy behavior i.e. it may take 3 clicks on a TapGestureHandler to get the modal dismissal to trigger.

I believe the reason for the problems is that the solution required extracting the modal contents into a separate functional component, but not sure how to address this. Here is the structure of my components. Would appreciate any guidance.

Before
```
<Modal>
   <TapGestureHandler> 
   ...
   </TapGestureHandler>
</Modal>
```

After
```
const ModalContents = gestureHandlerRootHOC(() =>
   <TapGestureHandler> 
   ...
   </TapGestureHandler>
);

<Modal>
   <ModalContents />
</Modal>
```

**Comment by mxmzb** [comment]
I've played around a bit and was able to find the issue. However, I am not sure what's causing it and how to fix it.

The problem in my case is, that I `react-native-gesture-handler` will **not** work inside a `@react-navigation/stack`, if placed inside a modal (so basically `Stack.Navigator` > `SomeScreenComponent` > `Modal` > `gestureHandlerRootHOC(PanGestureHandler)` fails). 

If I cut the Stack Navigator out or use the Tab Navigator, it works, so I am pretty sure it's the Stack Navigators' fault.

Relevant package versions:

```
react-native@0.61.5
@react-navigation/native@5.0.9
@react-navigation/stack@5.1.1
```

I'll try to setup a demo repo ASAP, let me know if I can provide any more helpful info.

**Comment by mxmzb** [comment]
Here is a demo app to (almost blank from `npx react-native init`), that will show the issue. You can toggle the stack navigator inside the app and see how the `PanGestureHandler` becomes functional and unfunctional.

https://github.com/mxmzb/react-native-breakable-app

**Comment by dicabrio** [comment]
I have a similar issue. It seems that the Stack.Navigator doesn't work well on Android. It doesn't matter if I use a mode="modal" or "card". 

So i was playing around and had the following code

`
import { SafeAreaView, Button } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack'

import { enableScreens } from 'react-native-screens';
enableScreens(); 

const Screen1 = ({ navigation }) => {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Button title="Open Modal" onPress={() => navigation.push('Modal')} />
      </SafeAreaView>
    )
  }

  const Screen2 = ({ navigation }) => {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Button title="Close Modal" onPress={() => navigation.goBack()} />
      </SafeAreaView>
    )
  }

const App = () => {

return (
        <NavigationContainer>
          <Stack.Navigator headerMode="none">
            <Stack.Screen name="Main" component={Screen1} />
            <Stack.Screen name="Modal" component={Screen2} />
          </Stack.Navigator>
        </NavigationContainer>
  )

}`

Then I removed this line;
`enableScreens();`

And then it worked correctly on Android.

**Comment by gideaoms** [comment]
A little trick to solve it inside a modal:

```js
import { TouchableWithoutFeedback } from 'react-native';
import { RectButton } from 'react-native-gesture-handler';
```

```js
<TouchableWithoutFeedback onPress={...}
    <RectButton>
         ...
    </RectButton>
</TouchableWithoutFeedback>
```

**Comment by amilaDulanjana** [comment]
I am having simillar issue. Any work around ?

**Comment by julianoddreis** [comment]
I was trying use https://github.com/osdnk/react-native-reanimated-bottom-sheet inside a modal, and it's not possible, I finally solved with react-navigation screen animation:

https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/143#issuecomment-614300015

**Comment by KawaljeetSBagga** [comment]
> A little trick to solve it inside a modal:
> 
> ```js
> import { TouchableWithoutFeedback } from 'react-native';
> import { RectButton } from 'react-native-gesture-handler';
> ```
> 
> ```js
> <TouchableWithoutFeedback onPress={...}
>     <RectButton>
>          ...
>     </RectButton>
> </TouchableWithoutFeedback>
> ```

Hey @gideaoms . I wonder how did your comment went unnoticed here. It definitely does the trick. Thanks man!

**Comment by chj-damon** [comment]
> Here is a demo app to (almost blank from `npx react-native init`), that will show the issue. You can toggle the stack navigator inside the app and see how the `PanGestureHandler` becomes functional and unfunctional.
> 
> https://github.com/mxmzb/react-native-breakable-app

then, what is the solution?

**Comment by AlexAlexandre** [comment]
I'm still having the same problem....
Any solution ou nothing yet ?

**Comment by cuddeford** [comment]
This is still a problem on 1.6.0

**Comment by VikasSahu** [comment]
Tried every suggestions mentioned above but still no luck yet. Please help its really frustrating.

**Comment by a-eid** [comment]
still an issue on `^1.7.0`

**Comment by moniquealtero** [comment]
Is still not working :/

**Comment by steniowagner** [comment]
Well, I found a possible workaround, it does exactly what we want and work for both iOS and Android.

https://www.youtube.com/watch?v=tLQjGHDiRkM

**Comment by a-eid** [comment]
@steniowagner is that like a custom modal ? I wouldn't recommend it 
just go with react-navigations or native-stack modal, it does work with it fine.

**Comment by steniowagner** [comment]
hmm, didn't test with react-navigations (sounded like too much for my case), but maybe it's the best way at the moment.

Thank you @a-eid !

**Comment by waheedakhtar694** [comment]
According to the docs 
https://docs.swmansion.com/react-native-gesture-handler/docs/#usage-with-modals-on-android

but still didn't work for me.

**Comment by waheedakhtar694** [comment]
@gideaoms that tricks may works for button but my use case is to use `PinchGestureHandler`  inside the modal.

> A little trick to solve it inside a modal:
> 
> ```js
> import { TouchableWithoutFeedback } from 'react-native';
> import { RectButton } from 'react-native-gesture-handler';
> ```
> 
> ```js
> <TouchableWithoutFeedback onPress={...}
>     <RectButton>
>          ...
>     </RectButton>
> </TouchableWithoutFeedback>
> ```

**Comment by mrousavy** [comment]
This issue is more than 2 years old, are there any plans to fix this?

I've created custom Slider components for my app and have to rewrite the whole thing since I'm using a lot of Modals...

**Comment by phanghos** [comment]
I've tried wrapping both the screen and the component with `gestureHandlerRootHoc` without success. I didn't try the `RectButton` approach because I need a `PanGestureHandler` in order to implement swipe-down-to-dismiss behaviour on the modal. It is frustrating because it works perfectly on iOS and, since I'm using `react-native-modal`, which comes with swipe-to-dismiss out-of-the-box, I've also tried using that approach instead and it works as long as you don't have scrollable content inside the modal because it's buggy both on iOS and Android, so I'm kind of stuck...

**Comment by mrousavy** [comment]
To sum up:

1. ❌ RNGH does **not** work in `react-native`'s `<Modal>` component (even though the Component is wrapped in a `gestureHandlerRootHOC`) 
2. ❌ RNGH does **not** work in a screen from `wix/react-native-navigation`'s which is shown using `Navigation.showModal` (even though the Screen is wrapped in a `gestureHandlerRootHOC`) 
3. ✅ RNGH apparently does work if shown using `react-navigation`'s push function with `modal: true`, but only when not using the native stack (`enableScreens()`/`createNativeStackNavigator()`). 

I can provide more details if required.

**Comment by flyskywhy** [comment]
[react-native-modal-animated](https://github.com/rafalkaczynsky/react-native-modal-animated) works with react-native-gesture-handler, because react-native-modal-animated creating a Modal just using a View.

**Comment by waheedakhtar694** [comment]
@flyskywhy if [react-native-modal-animated](https://github.com/rafalkaczynsky/react-native-modal-animated) doesn't use a separate activity like [react-native-modal](https://reactnative.dev/docs/modal) then how it's render on top of everything? If it's using an absolute position then it could make a problem in some cases.

**Comment by flyskywhy** [comment]
@waheedakhtar694 , at least in my case, no problem :stuck_out_tongue_closed_eyes:

**Comment by alessiocancian** [comment]
> @jvaclavik I used it in conjunction with https://github.com/callstack/react-native-paper, which has a component called [Portal](https://callstack.github.io/react-native-paper/portal.html) designed specifically for this purpose.

Solved using Portal from react-native-paper as @jvaclavik said.
I wrapped my App with PaperProvider, then changed Modals to Views and wrapped them with Portal.
Now bottom-sheet works on Android 😍

**Comment by GuruKarmakar** [comment]
Its working for me:
`<TouchableWithoutFeedback
                onPress={() => {
                  console.log("press");
                }}
              >
                <Text>
               <RectButton>
         ...
             </RectButton>
                </Text>
              </TouchableWithoutFeedback>`

**Comment by DavidAPears** [comment]
Any update on this? We have two projects where iOS is working as expected but Android modals are proving a headache. We'd rather not ave to remove modals from the projects...that's a big design overhaul.  :/

**Comment by a-eid** [comment]
@DavidAPears have you tried wrapping you modals in `gestureHandlerRootHOC` ? 

something like this ? 

```tsx

const ModalInner = gestureHandlerRootHOC(function GestureExample() {
  return (
    <View>
      <DraggableBox />
    </View>
  );
});

export default function ModalForX() {
  return (
    <Modal animationType="slide" transparent={false}>
      <ModalInner />
    </Modal>
  );
}


```

**Comment by dzbrozek** [comment]
Combination of `Portal` from `react-native-portalize` and `gestureHandlerRootHOC` works for me. Something like that:

```
<Portal>
   <Modal>
      <GestureHandlerRootHOCWrappedComponent />
   </Modal>
</Portal>
```

**Comment by IbrahimCanKALYA** [comment]
setting coverSreen={false} on modal works. But need my modal cover the screen

**Comment by zzzkasper-1995** [comment]
import {Platform, Modal} from 'react-native';
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';
import {AnimatedBottomSheet} from '../AnimatedBottomSheet';

const AnimatedBottomSheetWrapper = Platform.OS === 'android' ? gestureHandlerRootHOC(AnimatedBottomSheet) : AnimatedBottomSheet;

**Comment by fi-nik** [comment]
Not sure if this is going to help someone, i also had issues using this library with react-native-modal, but beside wrapping children of modal gestureHandlerRootHOC (this is working fine for buttons, but i had issues having text input in modal + avoidKeyboard = true and on every press of key, keyboard was closing ) So only thing i did, is made modal children wrapper, something like this:
`
const GestureHandlerWrapper = gestureHandlerRootHOC(
  ({ children }) => <View>{children}</View>,
  { flex: 0}
);

export const CustomModal: React.FC<Props> = ({
  children,
...rest
}) => {
  return (
    <Modal
      {...rest}
    >
      <GestureHandlerWrapper>    
          {children} 
      </GestureHandlerWrapper>
    </Modal>
  );
};
`

**Comment by WoLewicki** [comment]
Can you check if applying https://github.com/software-mansion/react-native-gesture-handler/pull/1323 fixes the issues?

**Comment by flyskywhy** [comment]
No, not fixes the issues by react-native-gesture-handler@1.10.2

And #1323 just modify ios? My problem related android :P


Wojciech Lewicki <notifications@github.com> 于2021年2月18日周四 下午9:55写道：

**Comment by WoLewicki** [comment]
Yes, I saw that it is issue of Android after commenting, my bad 😅

**Comment by lexguy** [comment]
> setting coverSreen={false} on modal works. But need my modal cover the screen



> setting coverSreen={false} on modal works. But need my modal cover the screen

it works for me , thanks ..

**Comment by lexguy** [comment]
> setting coverSreen={false} on modal works. But need my modal cover the screen

It works for me, thanks.
If you want to cover the screen , you can make a customed modal componnet and put it at the top level of component tree, then set style to cover screen, you can set children component (modal content) by Ref.

**Comment by baralong** [comment]
I got this working using the suggestion [for Library authors ](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors)
```html
<Modal>
    <GestureHandlerRootView style={{width:'100%', height:'100%'}}>
        <myGestureEnabledComponent/>
    </GestureHandlerRootView>
</Modal>
```

Only tested on my Pixel 5 so far, but things are looking good so far :smiley:

**Comment by imcyee** [comment]
> I got this working using the suggestion [for Library authors ](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors)
> 
> ```
> <Modal>
>     <GestureHandlerRootView style={{width:'100%', height:'100%'}}>
>         <myGestureEnabledComponent/>
>     </GestureHandlerRootView>
> </Modal>
> ```
> 
> Only tested on my Pixel 5 so far, but things are looking good so far

Works for nexus5x emulator.

**Comment by ntoporcov** [comment]
Wrapping your component in <GestureHandlerRootView> worked for me seamlessly!

**Comment by mfy5013** [comment]
None of the solutions here worked for me

**Comment by mfy5013** [comment]
After a whole day of debugging 
1. You need to wrap you RNGH components in gestureHandlerRootHOC
2. Wrap the modal in react-native-paper's <Portal>
3. Make sure the react native paper provider is the first component to render

When I did this it did not work:

![Screen Shot 2021-04-04 at 9 47 18 PM](https://user-images.githubusercontent.com/37169303/113529010-49262d00-9590-11eb-9dbc-8dfaebb5bdcb.png)

However this worked: 

![Screen Shot 2021-04-04 at 9 52 28 PM](https://user-images.githubusercontent.com/37169303/113529018-4f1c0e00-9590-11eb-8e72-7744c494ef30.png)

**Comment by Stevemoretz** [comment]
No at first I thought I use portal from paper and everything gets magically solved.
But use a textview in your modal now :)
It starts sucking.

**Comment by Stevemoretz** [comment]
> To sum up:
> 
> 1. ❌ RNGH does **not** work in `react-native`'s `<Modal>` component (even though the Component is wrapped in a `gestureHandlerRootHOC`)
> 2. ✅ RNGH does work in a screen from `wix/react-native-navigation`'s which is shown using `Navigation.showModal` (even though the Screen is wrapped in a `gestureHandlerRootHOC`)
> 3. ✅ RNGH apparently does work if shown using `react-navigation`'s push function with `modal: true`, but only when not using the native stack (`enableScreens()`/`createNativeStackNavigator()`).
> 
> I can provide more details if required.

if you had examples it would be great.

**Comment by flyskywhy** [comment]
> > setting coverSreen={false} on modal works. But need my modal cover the screen
> 
> It works for me, thanks.
> If you want to cover the screen , you can make a customed modal componnet and put it at the top level of component tree, then set style to cover screen, you can set children component (modal content) by Ref.

not worked when using stack of react-navigation

**Comment by flyskywhy** [comment]
> > I got this working using the suggestion [for Library authors ](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors)
> > ```
> > <Modal>
> >     <GestureHandlerRootView style={{width:'100%', height:'100%'}}>
> >         <myGestureEnabledComponent/>
> >     </GestureHandlerRootView>
> > </Modal>
> > ```
> > 
> > 
> > Only tested on my Pixel 5 so far, but things are looking good so far
> 
> Works for nexus5x emulator.

not worked when using stack of react-navigation

**Comment by flyskywhy** [comment]
> After a whole day of debugging
> 
> 1. You need to wrap you RNGH components in gestureHandlerRootHOC
> 2. Upgrade from  v1.8.0 to v1.10.3
> 3. Wrap the modal in react-native-paper's `<Portal>`
> 4. Make sure the react native paper provider is the first component to render
> 
> When I did this it did not work:
> 
> ![Screen Shot 2021-04-04 at 9 47 18 PM](https://user-images.githubusercontent.com/37169303/113529010-49262d00-9590-11eb-9dbc-8dfaebb5bdcb.png)
> 
> However this worked:
> 
> ![Screen Shot 2021-04-04 at 9 52 28 PM](https://user-images.githubusercontent.com/37169303/113529018-4f1c0e00-9590-11eb-8e72-7744c494ef30.png)
> 
> if i skip any one of these steps it does not work

not worked when using stack of react-navigation

**Comment by flyskywhy** [comment]
Months passed, I can't wait any more, to use react-native-gesture-handler in a modal when using stack of react-navigation, now I publish an `@flyskywhy/react-native-modal-animated` to npmjs.org, which is forked from [rafalkaczynsky/react-native-modal-animated](https://github.com/rafalkaczynsky/react-native-modal-animated), and replaced `componentWillReceiveProps` by React Hooks to support latest React

**Comment by oxilor** [comment]
RNGH works in a react native Modal if you wrap **ONLY** the content of the Modal in the `GestureHandlerRootView` component (see [RNGH docs](https://docs.swmansion.com/react-native-gesture-handler/docs/#usage-with-modals-on-android), [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-790329701) and [this pull request](https://github.com/software-mansion/react-native-gesture-handler/pull/937)).

But if you wrap the whole app (or a screen that contains the Modal) in `GestureHandlerRootView` too, RNGH buttons stops working inside the Modal (see why below).

Example of `GestureHandlerRootView` used only inside a Modal:
```tsx
const GHRVInsideModal: React.FC = () => {
  const [visible, setVisible] = useState(false);

  return (
    <>
      <TouchableOpacity onPress={() => setVisible(true)}>
        <Text>Open (it's RN button) - it works</Text>
      </TouchableOpacity>

      <Modal
        animationType="slide"
        transparent
        visible={visible}
      >
        <View style={styles.modal}>
          <RectButton onPress={() => setVisible(false)}>
            <Text>Close (it's RNGH button outside GestureHandlerRootView) - it does not work</Text>
          </RectButton>

          <GestureHandlerRootView>
            <RectButton onPress={() => setVisible(false)}>
              <Text>Close (it's RNGH button inside GestureHandlerRootView) - it works</Text>
            </RectButton>
          </GestureHandlerRootView>
        </View>
      </Modal>
    </>
  );
};
```

Example of nested `GestureHandlerRootView`:
```tsx
const NestedGHRV: React.FC = () => {
  const [visible, setVisible] = useState(false);

  return (
    <GestureHandlerRootView>
      <RectButton onPress={() => setVisible(true)}>
        <Text>Open (it's RNGH button) - it works</Text>
      </RectButton>

      <Modal
        animationType="slide"
        transparent
        visible={visible}
      >
        <View style={styles.modal}>
          <GestureHandlerRootView>
            <RectButton onPress={() => setVisible(false)}>
              <Text>Close (it's RNGH button inside GestureHandlerRootView) - it does not work</Text>
            </RectButton>

            <TouchableOpacity onPress={() => setVisible(false)}>
              <Text>Close (it's RN button) - it works</Text>
            </TouchableOpacity>
          </GestureHandlerRootView>
        </View>
      </Modal>
    </GestureHandlerRootView>
  );
};
```

Why does the button in the Modal work in the first case, but not in the second?
If we go to the 17 line of the [GestureHandlerRootView.android.tsx](https://github.com/software-mansion/react-native-gesture-handler/blob/master/src/GestureHandlerRootView.android.tsx#L17) file we see, that nested gesture handler root views renders as `View`. If you try to delete 17-22 lines from the `GestureHandlerRootView.android.tsx` file the second example starts working.

I don't use expo, but seems that expo wraps an app in `GestureHandlerRootView` automatically (correct me if I'm wrong). That's why, if you wrap only a modal in `GestureHandlerRootView`, trying to reproduce the first example, this root view will be rendered as `View` because a parent view already have the `GestureHandlerRootView` component.

See [this repo](https://github.com/oxilor/rngh-modal-bug) with two examples.

Video with two examples:

https://user-images.githubusercontent.com/35278731/123794634-b9bcbb80-d8eb-11eb-9780-bb7713652b33.mov

Video reproduced what will be if you delete 17-22 lines from the `GestureHandlerRootView.android.tsx` file (uploaded to YouTube, because GitHub does not allow to upload large files):
[![RNGH: nested GestureHandlerRootView renders as View](https://img.youtube.com/vi/Ey9dqLv__a4/0.jpg)](https://www.youtube.com/watch?v=Ey9dqLv__a4)

**Comment by Svarto** [comment]
> > After a whole day of debugging
> > 
> > 1. You need to wrap you RNGH components in gestureHandlerRootHOC
> > 2. Upgrade from  v1.8.0 to v1.10.3
> > 3. Wrap the modal in react-native-paper's `<Portal>`
> > 4. Make sure the react native paper provider is the first component to render
> > 
> > When I did this it did not work:
> > ![Screen Shot 2021-04-04 at 9 47 18 PM](https://user-images.githubusercontent.com/37169303/113529010-49262d00-9590-11eb-9dbc-8dfaebb5bdcb.png)
> > However this worked:
> > ![Screen Shot 2021-04-04 at 9 52 28 PM](https://user-images.githubusercontent.com/37169303/113529018-4f1c0e00-9590-11eb-8e72-7744c494ef30.png)
> > if i skip any one of these steps it does not work
> 
> not worked when using stack of react-navigation

I got this to work! Using react-navigation and react-native-paper. Amazing, thank you @mfy5013

**Comment by JeanJoskin** [comment]
Also ran into this problem. Based @oxilor 's solution I've made a wrapped Modal component (since it only happens there) to work around this. Hope it helps:

```typescript
import React from 'react';
import {PropsWithChildren} from 'react';
import {
  ModalProps,
  Platform,
  Modal as RNModal,
  requireNativeComponent,
  StyleSheet,
  ViewProps,
} from 'react-native';

const GestureHandlerRootViewNative = requireNativeComponent<ViewProps>(
  'GestureHandlerRootView',
);

const Modal = (props: PropsWithChildren<ModalProps>) => {
  if (Platform.OS === 'android') {
    return (
      <RNModal {...props}>
        <GestureHandlerRootViewNative style={StyleSheet.absoluteFill}>
          {props.children}
        </GestureHandlerRootViewNative>
      </RNModal>
    );
  } else {
    return <RNModal {...props}>{props.children}</RNModal>;
  }
};

export default Modal;
````

**Comment by thomas-coldwell** [comment]
The use of `react-native-portalize` fixed this perfectly for me while using React Navigation - here is a fully working Expo Snack for anyone that wants a minimal example of how to get this working in their own project:
https://snack.expo.dev/@thomascoldwell/react-navigation---rngh-root-view-bug-android---portal-fix

**Comment by joy-betterhalf** [comment]
@jakub-gonet When are you planning the next release with [#1603](https://github.com/software-mansion/react-native-gesture-handler/pull/1603) changes?

**Comment by jakub-gonet** [comment]
We're planning on releasing the next version in a month or so. This is a transition from 1.x to 2.x so it may take a bit longer than usual.

**Comment by eduardorfreitas93** [comment]
I'm trying to call the RectButton inside a transparentModal of createStackNavigator(@react-navigation/stack), on android the RectButton doesn't trigger onPress, IOS works perfectly

react-native-gesture-handler: 2.1.1
@react-navigation/native: ^6.0.6
@react-navigation/stack: ^6.0.11

Any solution?

**Comment by thahermps** [comment]
> The use of `react-native-portalize` fixed this perfectly for me while using React Navigation - here is a fully working Expo Snack for anyone that wants a minimal example of how to get this working in their own project:
> https://snack.expo.dev/@thomascoldwell/react-navigation---rngh-root-view-bug-android---portal-fix

Thanks a lot finally this solution worked for me. :)

**Comment by prasanthmurugasamy** [comment]
> 

need more assistance.! can you please help me with this?

**Comment by zhaiyjgithub** [comment]
For me, I just installed the newest version 2.4.0. And then I use **GestureHandlerRootView** to wrapper the **PanGestureHandler**. It works. Remember that don't wrapper the view or others components. Wrapper thePanGestureHandler like below:

`const $panelView = (
    <GestureHandlerRootView>
      <PanGestureHandler onGestureEvent={onGestureEvent}>
        <Animated.View style={[styles.panelView, panelStyle]}>
          {$contentView}
        </Animated.View>
      </PanGestureHandler>
    </GestureHandlerRootView>
  )`

**Comment by hugoh59** [comment]
> For me, I just installed the newest version 2.4.0. And then I use **GestureHandlerRootView** to wrapper the **PanGestureHandler**. It works. Remember that don't wrapper the view or others components. Wrapper thePanGestureHandler like below:
> 
> ```
>  const $panelView = (
>     <GestureHandlerRootView>
>       <PanGestureHandler onGestureEvent={onGestureEvent}>
>         <Animated.View style={[styles.panelView, panelStyle]}>
>           {$contentView}
>         </Animated.View>
>       </PanGestureHandler>
>     </GestureHandlerRootView>
>   )
> ```

This fix does make the component scrollable but it's still super glitchy on android compared to when using the same component outside of a modal.

**Comment by first-dev** [comment]
This happened to me too and belive it or not I solved it by setting **`backgroundColor`** to `transparent` (or any value)
I'm guessing because react-native optimizes views only used for positioning their children and removes them or something and having a `backgroundColor` forces it to keep the view (please correct me if I'm wrong).

**Comment by ser-emejia** [comment]
Still not working on Android 👎

**Comment by usedlife** [comment]
Try this: https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android

```jsx
const ExampleWithHoc = gestureHandlerRootHOC(() => (
    <View>
      <DraggableBox />
    </View>
  );
);

export default function Example() {
  return (
    <Modal>
      <ExampleWithHoc />
    </Modal>
  );
}
```

**Comment by Martijncvv** [comment]
> RNGH works in a react native Modal if you wrap **ONLY** the content of the Modal in the `GestureHandlerRootView` component (see [RNGH docs](https://docs.swmansion.com/react-native-gesture-handler/docs/#usage-with-modals-on-android), [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-790329701) and [this pull request](https://github.com/software-mansion/react-native-gesture-handler/pull/937)).
> 
> But if you wrap the whole app (or a screen that contains the Modal) in `GestureHandlerRootView` too, RNGH buttons stops working inside the Modal (see why below).
> 
> ## Examples
> Example of `GestureHandlerRootView` used only inside a Modal:
> 
> ```tsx
> const GHRVInsideModal: React.FC = () => {
>   const [visible, setVisible] = useState(false);
> 
>   return (
>     <>
>       <TouchableOpacity onPress={() => setVisible(true)}>
>         <Text>Open (it's RN button) - it works</Text>
>       </TouchableOpacity>
> 
>       <Modal
>         animationType="slide"
>         transparent
>         visible={visible}
>       >
>         <View style={styles.modal}>
>           <RectButton onPress={() => setVisible(false)}>
>             <Text>Close (it's RNGH button outside GestureHandlerRootView) - it does not work</Text>
>           </RectButton>
> 
>           <GestureHandlerRootView>
>             <RectButton onPress={() => setVisible(false)}>
>               <Text>Close (it's RNGH button inside GestureHandlerRootView) - it works</Text>
>             </RectButton>
>           </GestureHandlerRootView>
>         </View>
>       </Modal>
>     </>
>   );
> };
> ```
> 
> Example of nested `GestureHandlerRootView`:
> 
> ```tsx
> const NestedGHRV: React.FC = () => {
>   const [visible, setVisible] = useState(false);
> 
>   return (
>     <GestureHandlerRootView>
>       <RectButton onPress={() => setVisible(true)}>
>         <Text>Open (it's RNGH button) - it works</Text>
>       </RectButton>
> 
>       <Modal
>         animationType="slide"
>         transparent
>         visible={visible}
>       >
>         <View style={styles.modal}>
>           <GestureHandlerRootView>
>             <RectButton onPress={() => setVisible(false)}>
>               <Text>Close (it's RNGH button inside GestureHandlerRootView) - it does not work</Text>
>             </RectButton>
> 
>             <TouchableOpacity onPress={() => setVisible(false)}>
>               <Text>Close (it's RN button) - it works</Text>
>             </TouchableOpacity>
>           </GestureHandlerRootView>
>         </View>
>       </Modal>
>     </GestureHandlerRootView>
>   );
> };
> ```
> 
> Video with two examples:
> 
>  Screen.Recording.2021-06-29.at.15.06.01.mov 
> See [this repo](https://github.com/oxilor/rngh-modal-bug) with two examples.
> 
> ## React navigation
> If you create a Modal inside react-navigation's stack and wrap the content of the Modal in `GestureHandlerRootView` as the documentation says, it reproduces the second example and RNGH buttons in a Modal [will not work](https://github.com/software-mansion/react-native-gesture-handler/pull/937#issuecomment-779866856).
> 
> This is happening because react-navigation [wraps](https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Stack/StackView.tsx#L53) the stack content in `GestureHandlerRootView` and your GH root view in a Modal renders as a simple `View`.
> 
> ## How to fix
> Why does the button in the Modal work in the first case, but not in the second?
> 
> If we look at the 17th line of the [GestureHandlerRootView.android.tsx](https://github.com/software-mansion/react-native-gesture-handler/blob/master/src/GestureHandlerRootView.android.tsx#L17) file we see, that nested gesture handler root views renders as `View`. If you try to delete 17-22 lines from the `GestureHandlerRootView.android.tsx` file the second example will start working.
> 
> Video reproduced what will be if you delete 17-22 lines from the `GestureHandlerRootView.android.tsx` file (uploaded to YouTube, because GitHub does not allow uploading large files): [![RNGH: nested GestureHandlerRootView renders as View](https://camo.githubusercontent.com/f9a7bfd05530a96aed6ed2feb47dcf1af0c9d95bc98ab9bd19950790f91f275e/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f45793964714c765f5f61342f302e6a7067)](https://www.youtube.com/watch?v=Ey9dqLv__a4)
> 
> As a result, if the nested `GestureHandlerRootView` is NOT rendered as a simple `View`, RNGH buttons in a Modal in Android will work. I created a pull request #1493 that fixes it.

2023, problem is still there, but this worked. Thanks!

**Comment by Goowwy** [comment]
> > > I got this working using the suggestion [for Library authors ](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors)
> > > ```
> > > <Modal>
> > >     <GestureHandlerRootView style={{width:'100%', height:'100%'}}>
> > >         <myGestureEnabledComponent/>
> > >     </GestureHandlerRootView>
> > > </Modal>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Only tested on my Pixel 5 so far, but things are looking good so far
> > 
> > 
> > Works for nexus5x emulator.
> 
> not worked when using stack of react-navigation

Thanks its working for me

**Comment by ammarfaris** [comment]
> Thanks its working for me

Thanks for summarising @Goowwy . Works like a charm in Android modal! You all are life savers!

**Comment by steniowagner** [comment]
"react": "18.2.0",
"react-native": "0.72.5",
"react-native-gesture-handler": "^2.13.1"

Wrapping the components that uses the RNGH stuff works like a charm!

Thank you so much everyone!
