### ISSUE TITLE
Build fails on Android. RNGestureHandlerPackage not found

### ISSUE THREAD

**Issue by Humad** [software-mansion/react-native-gesture-handler#1683]
## Description
I'm trying to build my app for android by doing `./gradlew bundlerelease`, but I am getting errors. (See below for details)

## Steps To Reproduce

1. Follow installation instructions here: https://docs.swmansion.com/react-native-gesture-handler/docs/#installation
2. Try to build the android app by doing `./gradlew bundlerelease`

### Expected behavior

App builds successfully

### Actual behavior

App does not build.

Getting the following error:

```
> Task :app:compileReleaseJavaWithJavac FAILED
/Users/humad-home/tvproject-mobile/android/app/src/main/java/com/serializdmobile/MainApplication.java:11: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/humad-home/tvproject-mobile/android/app/src/main/java/com/serializdmobile/MainApplication.java:12: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/humad-home/tvproject-mobile/android/app/src/main/java/com/serializdmobile/MainApplication.java:13: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/humad-home/tvproject-mobile/android/app/src/main/java/com/serializdmobile/MainApplication.java:14: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/humad-home/tvproject-mobile/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:33: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/humad-home/tvproject-mobile/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:104: error: cannot find symbol
      new RNGestureHandlerPackage(),
          ^
  symbol:   class RNGestureHandlerPackage
  location: class PackageList
Note: /Users/humad-home/tvproject-mobile/android/app/src/main/java/com/serializdmobile/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

FAILURE: Build failed with an exception.

```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: git://github.com/software-mansion/react-native-gesture-handler.git#5572e8d65d73889f0bdb91f5aaa33cc1958971cd  
(For React Native Gesture Handler, I'm on the above commit which fixes modal issues)

# Other notes
This is only an issue with Android. The iOS app builds perfectly.
I was able to build the Android app a few days ago. Not sure why it has stopped building now. I can't find anything in my project's commit history that indicates a breaking change.

**Comment by mwegener-com** [comment]
same problem. How did you solve it?

**Comment by mwegener-com** [comment]
Fixed it by:
npm install this repo
npx jetify

**Comment by Arkan4ik** [comment]
@mwegener-com have you found solution?

**Comment by mwegener-com** [comment]
> @mwegener-com have you found solution?

There are some other threads about this issue.

**Comment by veb-ioki** [comment]
Did anyone find a real solution for this?
(or this https://github.com/software-mansion/react-native-gesture-handler/issues/1707)

We have the same issue when trying to update from 2.2.0 to 2.5.0, Android build fails with:

```
/Users/<xxx>/<xxx>/<xxx>/android/app/src/main/java/com/<xxx>/<xxx>/MainApplication.java:23: error: cannot find symbol
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
                                         ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler.react
/Users/<xxx>/<xxx>/<xxx>/android/app/src/main/java/com/<xxx>/<xxx>/MainApplication.java:58: error: cannot find symbol
            packages.add(new RNGestureHandlerPackage());
                             ^
  symbol: class RNGestureHandlerPackage
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
```
### Package versions
* React: 17.0.2
* React Native: 0.68.2
* existing version of React Native Gesture Handler: 2.2.0

iOS builds fine

**Comment by veb-ioki** [comment]
This is still an issue with react-native-gesture-handler 2.6.0.
Exact same build failure.

**Comment by veb-ioki** [comment]
In case others are as blind and stupid as I was, this is what the problem was (for us):
We hadn't read the docs thoroughly enough 🤦‍♀️ and didn't update the `MainActivity.java` as instructed for migration to rn-gesture-handler 2:
https://docs.swmansion.com/react-native-gesture-handler/docs/guides/upgrading-to-2
https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot/

And as we are using rn-gesture-handler along with React Navigation, we also needed to do [this](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot#update-your-js-code) is needed as well, because otherwise the app did not "work correctly" as mentioned said [here](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot#check-if-your-app-works-correctly).

**Comment by erickcrus** [comment]
Same issue.
Using react-native-gesture-handler 2.5.0 with react-native 0.65.

I just reinstall package with `npm install react-native-gesture-handler` and `npx jetify`, but I still have the issue `cannot find symbol. import com.swmansion.gesturehandler.RNGestureHandlerPackage`

**Comment by tgreco** [comment]
Running into this issue as well.

**Comment by gabriel-messas** [comment]
Having this issue right after updating to the latest react-native@0.72.0

**Comment by dgreasi** [comment]
Same issue with the following dependencies:

```
"react": "18.2.0",
"react-native": "0.72.3",
"react-native-gesture-handler": "^2.12.0",
"react-native-reanimated": "^3.3.0",
"@react-navigation/bottom-tabs": "^6.5.8",
"@react-navigation/elements": "^1.3.3",
"@react-navigation/native": "^6.0.10",
"@react-navigation/native-stack": "^6.6.2",
```

**Comment by tchejanovich** [comment]
Hi, I'm still having this issue. 
```
"react-native": "0.70.0",
"react-native-gesture-handler": "2.10.0",
```
None of the solutions above works for me.

**Comment by BiigBan** [comment]
Hey, I noticed same issue when downloaded package with yarn. I deleted whole node_modules and installed it again(npm install). Now it works fine. As far as I understand the main problem with yarn, I used npm before and in this case installed package with yarn.
If you are used npm before - try to install new package with npm(don`t use yarn) and your app will build succesfully

**Comment by phillipkey** [comment]
If you have manual dependency linking in your project, you should double check the import path for `com.swmansion.gesturehandler.RNGestureHandlerPackage;` in your MainApplication. 

We were updating from 1.10.3 -> 2.5.0 and it looks like at some point the import path for the package was moved from 
`import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;` to `import com.swmansion.gesturehandler.RNGestureHandlerPackage;`

**Comment by kyeyunedaniel** [comment]
> react-native-gesture-handle

Thanks, ur suggestion seemed to fix my issue.

**Comment by ivanrndev-leo** [comment]
`./gradlew clean` helped me
