### ISSUE TITLE
undefined method `install_dependencies' for Pod:Module

### ISSUE THREAD

**Issue by krunaldarji** [software-mansion/react-native-gesture-handler#2645]
### Description

When i am using pod install command getting below error:

```
[!] Invalid `Podfile` file: 
[!] Invalid `RNGestureHandler.podspec` file: undefined method `install_dependencies' for Pod:Module
Did you mean?  instance_exec.

 #  from /Users/XXXX/Documents/MyApps/OK_RN/node_modules/react-native-gesture-handler/RNGestureHandler.podspec:48
 #  -------------------------------------------
 #    else
 >      install_dependencies(s, new_arch_enabled)
 #    end
 #  -------------------------------------------
```

### Steps to reproduce

1. npm i
2. cd ios
3. arch -x86_64 pod install     

### Snack or a link to a repository

xx

### Gesture Handler version

2.9.0

### React Native version

0.68.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Shiro1995** [comment]
same issue

**Comment by nasamanaosoftware** [comment]
same issue

**Comment by SvenWD** [comment]
```
    "react-native": "0.70.13",
    "react-native-gesture-handler": "^2.13.3",
```

I have the same problem.

**Comment by CNTMobile** [comment]
try using "react-native-gesture-handler": "^1.8.0", it works for me

**Comment by nasamanaosoftware** [comment]
> try using "react-native-gesture-handler": "^1.8.0", it works for me

This works for me, still it should be a temporary solution, `undefined method 'install_dependencies' for Pod:Module` problem should be fixed with the latest version of react-native-gesture-handler.

**Comment by sakshi-shell** [comment]
we also having the same issue.

**Comment by darimuhittinhey** [comment]
Same issue here !!

**Comment by alihaydar56** [comment]
Same issue here !!
```
 "react-native-gesture-handler": "^2.13.3",
  "react-native": "^0.70.6",
   "react-native-reanimated": "^2.13.0",
```

**Comment by alihaydar56** [comment]
> > Same issue
> > `"react-native-gesture-handler": "^2.9.0"`
> > `"react-native-reanimated": "^2.14.4",`

*downgrade react-native-gesture-handler version to ^1.8.0 temporary

**Comment by erickcrus** [comment]
any solution?

**Comment by benminor** [comment]
TEMPORARY SOLUTION: change your version to 2.9.0 (no ^) 

package.json
```"react-native-gesture-handler": "2.9.0",```

**Comment by emre-atilla** [comment]
> TEMPORARY SOLUTION:
> 
> 1. Change your version to 2.9.0 (without the ^)
> 2. Delete node_modules & package-lock.json
> 3. run `npm i && cd ios/ && pod install`
> 
> package.json `"react-native-gesture-handler": "2.9.0",`



This is fixed my problem thanks.

**Comment by a-luengen** [comment]
Experienced the same issue today. I noticed the only difference between one of our working react-native app projects and the failing one was that the error occured when upgrading to latest `"react-native-gesture-handler": "2.13.3"`.

Solution:
1. Set version to `2.13.2` in `package.json`
2. run `npm i && ios/ && pod install`

**Comment by m-bert** [comment]
Maybe I could have phrased it better. If reinstalling `pods` and `node_modules` fixes that problem, there is no need to release new version.

Also, @a-luengen, have you tried steps that I'm talking about on `2.13.3`? I'm almost sure that it doesn't have to do anything with the version of Gesture Handler, since you and @benminor used different versions, yet followed the same path to fix this issue.

**Comment by j-piasecki** [comment]
Could you install Gesture Handler 2.13.3, verify that it's still broken, and check if the following patch solves the problem?
[react-native-gesture-handler+2.13.3.patch](https://github.com/software-mansion/react-native-gesture-handler/files/13067885/react-native-gesture-handler%2B2.13.3.patch)
