### ISSUE TITLE
'React/RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by chillyprig** [software-mansion/react-native-gesture-handler#299]
Here what I found

<img width="871" alt="screen shot 2561-09-30 at 18 18 09" src="https://user-images.githubusercontent.com/7731552/46257030-37560180-c4dd-11e8-9557-0c8b433405b7.png">

I use expo and eject it.

react-native link works fine

<img width="558" alt="screen shot 2561-09-30 at 18 19 15" src="https://user-images.githubusercontent.com/7731552/46257032-5fddfb80-c4dd-11e8-9213-8dd4815dbf96.png">

pod install works fine

<img width="570" alt="screen shot 2561-09-30 at 18 20 33" src="https://user-images.githubusercontent.com/7731552/46257044-8a2fb900-c4dd-11e8-8e3e-9793d21145be.png">

Already did config the scheme React

<img width="889" alt="screen shot 2561-09-30 at 18 21 40" src="https://user-images.githubusercontent.com/7731552/46257053-b814fd80-c4dd-11e8-9202-705ef0159a20.png">

Already config Header Search Path

<img width="498" alt="screen shot 2561-09-30 at 18 22 33" src="https://user-images.githubusercontent.com/7731552/46257079-0924f180-c4de-11e8-803f-b4c498af09fd.png">
<img width="499" alt="screen shot 2561-09-30 at 18 22 53" src="https://user-images.githubusercontent.com/7731552/46257080-0b874b80-c4de-11e8-8f36-349c96247976.png">
<img width="502" alt="screen shot 2561-09-30 at 18 23 58" src="https://user-images.githubusercontent.com/7731552/46257081-0cb87880-c4de-11e8-93bd-35091c506e1a.png">

Here is my package.json

<img width="591" alt="screen shot 2561-09-30 at 18 24 54" src="https://user-images.githubusercontent.com/7731552/46257100-48ebd900-c4de-11e8-98f3-b516dfd09738.png">

Now I don't know what to do next. I googled and followed all what I can. Nothing worked.

You guys are my last hope, before I delete React Native project and re-write it all over again with the Pure Native one.

**Comment by osdnk** [comment]
@chillyprig 
This issue appears to be quite common. Could you please use `Product -> clean` and then `react-native start --reset-cache`

**Comment by chillyprig** [comment]
Thanks @osdnk I did what you've suggest.

<img width="1361" alt="screen shot 2561-10-01 at 21 38 37" src="https://user-images.githubusercontent.com/7731552/46295515-71e59a00-c5c2-11e8-91e6-7f03d17bfeac.png">

The problem still persist in my case. I really appreciated your help.

**Comment by osdnk** [comment]
Won't you like to try with official `react-native` version?

**Comment by osdnk** [comment]
Have you tried with legacy build system?

**Comment by osdnk** [comment]
This issue appears to be inactive. If you still face the problem, please let us know

**Comment by KaneNguyen** [comment]
> This issue appears to be inactive. If you still face the problem, please let us know

Hi osdnk,
my issue is same @chillyprig 
 "react-native": "^0.57.4",
and i'm use cocoapod

**Comment by gigeos** [comment]
I have the same product because I have pod file and so I has conflict with react from ./node_modules and ./Pods. So I deleted React from Pods but now I don't know what I have to do to resolve my problem

**Comment by TomBerriot** [comment]
@osdnk Same problem here, clearing every cache I could never resolved my issue.

Though replacing all `#import <React/XXX>` by `#import "XXX"`, it is in any way a solution as these files are always suppressed and redownloaded.

Even compiling RNGestureHandler alone doesn't work, there seems to be an issue with how RNGestureHandler access React libraries that others don't have.

Would it be related to the old version of React (0.11.0) added and referenced in `Podfile.lock` by RNGestureHandler ?

**In Podfile.lock**
```
  - React (0.11.0):
    - React/Core (= 0.11.0)
  - React/Core (0.11.0)
  - RNGestureHandler (1.0.12):
    - React
```

I'm know little about Swift/Objective-C and Xcode. I've also cleaned Xcode project and rebuild multiple times and this doesn't do anything.

**Comment by haluong89** [comment]
same issue here, and I couldn't resolve it. I hope, someone can help me with this:)

**Comment by osdnk** [comment]
I have found similar issue here:
**https://github.com/bugsnag/bugsnag-react-native/issues/193**
Could you try following it?

**Comment by ifyapishore** [comment]
Same issue here:
Nothing helps:
- Clearing caches
- Reinstall node, npm, node_modules etc.
- Clearing XCode build artifacts (on disk and from menu)
- Removal of Podfile
- Manual linking and thought react-native link
- Global reset (remove project, remove node and npm from dev box, checkout again, link libraries by instructions).

Eventually I modified Podfile manually (with all dependencies) and it finally start compiling. I do not publish it because it will definitely will not work for everyone.
After that it failed with "jsbundle not found" (and it is actually missing).

Nice :) After week of nightmare I have no clue why it stop working in first place and what to do next.

**Comment by SteffeyDev** [comment]
I was able to fix this by adding the following to my `ios/Podfile`:
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation',
  # Add any other subspecs you want to use in your project
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Third party deps podspec link
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

When I ran `pod update`, I noticed this: `Installing React 0.58.0-rc.2 (was 0.11.0)`
This means that @TomBerriot was correct about the old react version, and if you don't manually specify the React pod in your Podfile, it will try to use the older version of React, which doesn't allow for the `<React/RCTEventDispatcher.h>` syntax.

**Comment by naoey** [comment]
I can confirm that @SteffeyDev 's solution worked for me as well. None of the other solutions work. It seems that this is indeed to do with an outdated version of the React Pod being installed.

**Comment by brave-merida** [comment]
Follows works good.
- remove Pods, Podfile.lock
- remove `pod RNGestureHandler` in `Podfile`
- `pod install`

**Comment by karenerobinson** [comment]
I have this problem but when I modify the Podfile per @SteffeyDev's comment I get:

> [!] No podspec found for `React` in `./node_modules/react-native`

What's supposed to put the podspec into the 'node_modules' folder?  Do I need to add something to npm's 'package.json' ?

**Comment by naoey** [comment]
@karenerobinson are you sure you've added the path to the podspec correctly? Your log says `./node_modules/react-native`, when in a standard RN project structure the path to node_modules would be a level above the Podfile which would make it `../node_modules/react-native`

**Comment by blueturtle13g** [comment]
> Follows works good.
> 
> * remove Pods, Podfile.lock
> * remove `pod RNGestureHandler` in `Podfile`
> * `pod install`
>   and then Build!

I can't believe it, but just your solution solved my problem thanks man!

**Comment by hugoh59** [comment]
The app is likely to crash at some point if you remove RNGestureHandler.

**Comment by justinsymph** [comment]
![Screenshot 2019-09-16 at 3 23 21 PM](https://user-images.githubusercontent.com/45754798/64949049-f1cd4880-d895-11e9-8c56-ecec7f70aa4d.png)

I tried every solution out there, but still, no luck fixing this.
Using version: `"react-native-gesture-handler": "1.4.1"`

**Comment by ferrannp** [comment]
I was facing this same issue yesterday when updating from `react-native-gesture-handler` `1.0.16` to `1.5.0`. In the past I linked `react-native-gesture-handler` with `react-native link` (even that I have pods too). What I did is run `react-native unlink react-native-gesture-handler` and then I add it into pods:

```ruby
pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
```

That might be useful for anyone landing here :)

**Comment by ue** [comment]
upgrading with `rn +60` to the latest `gesture handler` version **solution**.
Do not put into your podfile!

Follow these steps;
Go Libraries folder from remove `RnGesutreHandler.xscodeproj`
Go header search under build settings remove `GestureHanler paths`
Go general section remove `libRNGestureHandler` from Frameworks and libraries

**Comment by dean-scott** [comment]
@ferrannp  fix worked for me.  Thanks, I was pulling out my hair.

**Comment by jakub-gonet** [comment]
Should be resolved in newer versions.

**Comment by BatDroid** [comment]
I still had this issue with a legacy code that was given to me...
I removed the gesture handler lib from `Link Binary with Libraries` and kept the podfile and it's working now

**Comment by haveamission** [comment]
@jakub-gonet I'm still seeing it on 1.10.2

**Comment by rabiaah** [comment]
Same issue still here 

"react-native-gesture-handler": "~1.10.2",


node_modules/expo-modules-core/ios/NativeModulesProxy/EXNativeModulesProxy.m:9:9: 'React/RCTEventDispatcherProtocol.h' file not found

![image](https://user-images.githubusercontent.com/21026029/142645512-11da475a-2858-4397-a710-fd0ccae81dd2.png)

**Comment by dfabreguette-ap** [comment]
I also have the problem since today, as I ugpraded my platform to ios 12 and updated  expo-modules-core.
Any idea how I can solve that ?
<img width="1498" alt="Capture d’écran 2021-11-22 à 12 37 39" src="https://user-images.githubusercontent.com/7055931/142855282-94c8ffa1-515c-4270-b6ac-315df06d6e47.png">

**Comment by reisvini1** [comment]
Any ideia on how to solve it?

**Comment by dfabreguette-ap** [comment]
@reisvini1 In case it can help, I solved the issue by downgrading expo SDK to v41 (as it was before upgradeing). This expo SDK version does not use expo-core-modules.

**Comment by YahyaBagia** [comment]
Any updates on this ? I have the exact same problem..


> I also have the problem since today, as I ugpraded my platform to ios 12 and updated expo-modules-core. Any idea how I can solve that ? <img alt="Capture d’écran 2021-11-22 à 12 37 39" width="1498" src="https://user-images.githubusercontent.com/7055931/142855282-94c8ffa1-515c-4270-b6ac-315df06d6e47.png">

**Comment by rabiaah** [comment]
**The solution from my side was as below:**

I've run the below to upgrade the **expo-cli**

> sudo npm install --global expo-cli


_Recommendation is to do reboot and retry again._

**Comment by reisvini1** [comment]
Solve it by upgrading the project to use EAS build instead of bare workflow.

**Comment by zain-khalid** [comment]
I got the same issue. Here is the solution that work for me.

My React Native version is 0.63.4. As mentioned in https://www.npmjs.com/package/react-native-blob-util that the latest version is not compatible for react native version less than 0.65.X. 

DO This
react-native-blob-util : 0.17.2 -> 0.16.5 

pod clean
pod install

clean build folder and install the app
