### ISSUE TITLE
ReanimatedSwipeable's Left Swipeable Card is not working after Expo SDK53 update

### ISSUE THREAD

**Issue by farhadjaman** [software-mansion/react-native-gesture-handler#3643]
### Description

After upgrading from Expo SDK 52 to Expo SDK 53, the left-action button inside my ReanimatedSwipeable (from react-native-gesture-handler) no longer receives press events on iOS—unless the New Architecture (Fabric) is enabled. With Fabric disabled, tapping the left action button does not invoke its onPress handler at all, regardless of the button’s width. I have disabled the new architecture because of some UI related issues

https://github.com/user-attachments/assets/f36be0b9-a225-4b93-82f6-157879fe88b7

### Steps to reproduce

1. Create a ReanimatedSwipeable with a left action button:
2. Disable the New Architecture (Fabric) in iOS/Podfile or via Expo config plugin.
3. Make sure you are using the new EXPO SDK53
4. Swipe right to reveal the red “Delete” button.
5. Tap anywhere on the red “Delete” button.

### A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.

https://gist.github.com/farhadjaman/46e6a0d10bb2d181b54104ad6524ec98

### Gesture Handler version

2.24.0

### React Native version

0.79.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Using Expo Prebuild or an Expo development build

### Architecture

Old Architecture (Paper)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by RalissonMattias** [comment]
Here too! In my case it breaks in both directions and throws an error. Obs: I'm not using Expo

React Native CLI: 0.79.5
Reanimated: 4.0.1
Gesture Handler: 2.27.2
New Arch: ON

<img width="415" height="841" alt="Image" src="https://github.com/user-attachments/assets/f2a0ef5e-19c6-42be-b6da-ad973e815844" />

**Comment by deepktp** [comment]
@RalissonMattias 

i had this issue fixed with an simple patch by changing import path from `.` to `./index`

issue was on `react-native-gesture-handler: "2.28.0"`  with `react-native: "81.4"`

got to file `node_modules/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx`
```diff
- import { SwipeableProps, SwipeableMethods, SwipeDirection } from '.';  //line 14 on my system 
+ import { SwipeableProps, SwipeableMethods, SwipeDirection } from './index';
```

**Comment by Vashiru** [comment]
Also happens to me without Expo using just plain RN 0.81.4 and react-native-gesture-handler 2.28.0 and react-native-reanimated 3.19.1 on Android.

When swiping an item to the right, the items on the left become visible but the pressables within don't register a touch/click. Just moving those over to renderRightActions and changing leftThreshold to rightThreshold, demonstrates the exact same code working on the right.

I only have this issue on Android though, on iOS the items can be touched. I tried @deepktp's solution, but it was to no avail unfortunately.

**Comment by Vashiru** [comment]
I've created a minimal reproducible case based on the reproducer repo (RN, no Expo) here: https://github.com/Vashiru/left-actions-swipe-unclickable-bug

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/b3d4cc55-df89-4f78-aedb-c5defe67d458" />

Note that on iOS this works fine, **it's on Android where the issues appear**, it's just easier to take a screenshot on the iOS simulator (hence the counter set to 2). It doesn't matter if there are only left actions present or both left and right, it happens in both cases.

**Comment by Vashiru** [comment]
@m-bert @latekvo, sorry in advance if it's not the right practise to tag you: I've added a repro, but the labels don't reflect this. The issue is also (for me at least) not failing on iOS but rather on Android and without Expo. If you're using this component with actions on the left, the library is currently not compatible with 0.81.

Please let me know if more information is required to reproduce / investigate the issue.

**Comment by Valli-** [comment]
Seeing same problem, any solution yet?

**Comment by latekvo** [comment]
@RalissonMattias Hey, this looks like a duplicate of #3720. While the setup is slightly different, the error is identical. This issue will be fixed with #3666, we'll merge and release that PR soon.

@Vashiru Thanks a lot for the reproducer app, I'm looking into it right now.

> sorry in advance if it's not the right practise to tag you

That ping is alright, it was completely justified, this is kind of an urgent issue.

**Comment by dc-full-dev** [comment]
A quick, temporary solution is to add pointerEvents="box-none" to the const leftElement in <Animated.View> along this path `node_modules/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx`

**Comment by sidorchukandrew** [comment]
We are seeing this on RN 79 and old arch as well. We were able to track it down to these two styles conflicting with one another: [leftActions](https://github.com/software-mansion/react-native-gesture-handler/blob/main/packages/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx#L598) and [rightActions](https://github.com/software-mansion/react-native-gesture-handler/blob/main/packages/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx#L603). When we comment out the rightActions style, left actions is able to receive press events again. Should we open another issue? @latekvo

**Comment by alexsegura** [comment]
@dc-full-dev where are you supposed to add `pointerEvents="box-none"`? I tried but with no luck.

**Comment by alexsegura** [comment]
@latekvo hi, sorry for the ping again, but do you have news on this? 
We would like to migrate from `react-native-swipe-list-view` but are blocked by this one. Thanks!

**Comment by latekvo** [comment]
@alexsegura Hey, sorry, there aren't any news on this from me. For now I won't be able to work on this issue unfortunately. There's a chance other maintainers will work on this in the future, but that isn't a guarantee. 

One thing though, could you try bumping reanimated **and worklets** to the latest release?
There's [this](https://github.com/software-mansion/react-native-reanimated/issues/6659#issuecomment-3474023338) issue, which IIRC has a very similar underlaying root cause, and someone managed to get it fixed by bumping worklets and expo.

**Comment by Vashiru** [comment]
> [@alexsegura](https://github.com/alexsegura) Hey, sorry, there aren't any news on this from me. For now I won't be able to work on this issue unfortunately. There's a chance other maintainers will work on this in the future, but that isn't a guarantee.
> 
> One thing though, could you try bumping reanimated **and worklets** to the latest release? There's [this](https://github.com/software-mansion/react-native-reanimated/issues/6659#issuecomment-3474023338) issue, which IIRC has a very similar underlaying root cause, and someone managed to get it fixed by bumping worklets and expo.

Now that https://github.com/software-mansion/react-native-reanimated/issues/8235 has been fixed, I've been able to upgrade to react-native-reanimated v4 (before that the app just kept crashing). So I've updated to the latest version, as well as the latest worklets (at the time of writing v4.1.5 and v0.6.1 respectively) and the issue unfortunately persists.

To be safe I've also updated react-native-gesture-handler to v2.29.1.

**Comment by Vashiru** [comment]
Did some more testing: react-native 0.82.1 doesn't resolve the issue either.

**Comment by V-Babayan** [comment]
> We are seeing this on RN 79 and old arch as well. We were able to track it down to these two styles conflicting with one another: [leftActions](https://github.com/software-mansion/react-native-gesture-handler/blob/main/packages/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx#L598) and [rightActions](https://github.com/software-mansion/react-native-gesture-handler/blob/main/packages/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx#L603). When we comment out the rightActions style, left actions is able to receive press events again. Should we open another issue? [@latekvo](https://github.com/latekvo)

i had some issue, and i wrote patch for it

```
--- a/node_modules/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx
+++ b/node_modules/react-native-gesture-handler/src/components/ReanimatedSwipeable/ReanimatedSwipeable.tsx
@@ -359,6 +359,7 @@ const Swipeable = (props: SwipeableProps) => {
   const leftActionAnimation = useAnimatedStyle(() => {
     return {
       opacity: showLeftProgress.value === 0 ? 0 : 1,
+      zIndex: showLeftProgress.value >= 1 ? 1 : 0,
     };
   });
```

**Comment by m-bert** [comment]
I've closed this issue as duplicate of #3223 to keep discussion in one place.

We are aware of this problem, but for now we don't have viable solution. If we do have one, we will inform you in the issue mentioned above. 

For now you can try [patch with `zIndex`](https://github.com/software-mansion/react-native-gesture-handler/pull/3236#issuecomment-2782298812), but we do not guarantee that it won't break anything else.
